### PR TITLE
Remove the Sankey View (#313)

### LINKED ISSUE #313: Remove the Sankey view
#### Description
The Sankey View doesn't render the Sankey. 
An error message reads: 
> Invalid format in datatable: column #2 must be of type 'number'.

_(FYI: Not sure if we're going forward with the Sankey view at all yet)._

#### Screenshots

Image

_I tested some fake data_, to ensure the data was the issue. _Example of what it should look like obviously:_

Image

#### Possible files
`WrapperSankey.tsx`

#### Found With
Luke's PC, random dummy dataset, development mode

#### To Reproduce
Click Sankey view

#### Theories
The `sankeyData` is not being generated in the proper format.

Example proper format:
`export const data = [
  ["From", "To", "Weight"],
  ["A", "X", 5],
  ["A", "Y", 7],
  ["A", "Z", 6],
  ["B", "X", 2],
  ["B", "Y", 9],
  ["B", "Z", 4],
];`

#### Possible Steps
- [ ] Ensure that sankeyData is being generated in the correct format

### PR DESCRIPTION
**Pull request by Luke-Schreiber**
### Does this PR close any open issues?
Closes #313 

### Give a longer description of what this PR addresses and why it's needed
We decided we no longer need the Sankey View.

This PR:

- Deletes `WrapperSankey.tsx` and its parent folder 'Sankey'
- Removes the only reference of `WrapperSankey`

### Have you added or updated relevant tests?
- [ ] Yes
- [X] No changes are needed

### Have you added or updated relevant documentation?
- [ ] Yes
- [X] No changes are needed

### Are there any additional TODOs before this PR is ready to go?

TODOs:
- [ ] ...

### CODE REVIEW

File: frontend/src/Components/Charts/Sankey/WrapperSankey.tsx [hunk 1]
```diff
@@ -1,234 +0,0 @@
-import { Typography } from '@mui/material';
-import { observer } from 'mobx-react';
-import {
-  useContext, useEffect, useState,
-} from 'react';
-import Chart from 'react-google-charts';
```
Comment (JackWilb) [inline frontend/src/Components/Charts/Sankey/WrapperSankey.tsx:6]: We'll need to remove this package from the package.json. Please also check if there are any others that need to be removed

File: frontend/src/Dashboard.tsx [hunk 2]
```diff
@@ -40,20 +39,13 @@ function Dashboard() {
             centered
           >
             <Tab label="Main Dashboard" />
-            <Tab label="Sankey" />
```
Comment (JackWilb) [inline frontend/src/Dashboard.tsx:43]: We can remove all the tabs for now. We will maybe add this back later, but no reason to keep the one tab

**Review by JackWilb — CHANGES_REQUESTED** [review]

File: frontend/src/Dashboard.tsx (hunk 2 above)
Comment (Luke-Schreiber) [reply frontend/src/Dashboard.tsx:43]: Removed all tabs https://github.com/visdesignlab/Sanguine/pull/318/commits/0593ff02e1e60785a9edab12f397f51878cbaa66

File: frontend/src/Components/Charts/Sankey/WrapperSankey.tsx (hunk 1 above)
Comment (Luke-Schreiber) [reply frontend/src/Components/Charts/Sankey/WrapperSankey.tsx:6]: [e71f993](https://github.com/visdesignlab/Sanguine/pull/318/commits/e71f993b745afb6992e413472b4891b7846e5e95)  Removed unused packages - but there's a small build error I'm getting after the latest yarn install. I'll work on it.

**Review by JackWilb — APPROVED** [review]
