### PR TITLE
Fix: Heatmap Attribute Data Scaling (#312)

### LINKED ISSUE #312: Heatmap's additional attribute datapoints escape boundary
#### Description
In specifically the heatmap, when additional attributes `Preop HGB` and `Postop HGB` are added, their datapoints escape the column boundary (they should be contained and scaled correctly). When clicking `APR-DRG Weight` the datapoints are so spread out they reach into the heatmap itself.

#### Screenshots

Image

With `APR-DRG Weight`, datapoints everywhere.

Image

#### Possible files
Possibly `GeneratorExtraPair.tsx`

#### Found With
Luke's PC, random dummy dataset, development mode

#### To Reproduce
- Add Heatmap
- Add additional attribute of `Preop HGB` or `Postop HGB` or `APR-DRG Weight` 

#### Theories
Given that the Cost-Savings chart does not have this issue, I doubt this is strictly a data problem, but a rendering problem.

#### Possible Steps
- [ ] Compare how cost-savings chart renders its additional attributes vs heatmap
- [ ] Ensure that `Preop HGB` or `Postop HGB` or `APR-DRG Weight` have data contained correctly.

### PR DESCRIPTION
**Pull request by Luke-Schreiber**
### Does this PR close any open issues?
Closes #312 

### Give a longer description of what this PR addresses and why it's needed

Issue #312: Datapoints were scattered out-of-bounds in 'additional attribute' columns which contain violin plots

This PR:

- Changes the datapoint scaling from static domains to dynamic data-based domains.
- Ensures that all violin plots and datapoints (within each additional attribute) internally have the same horizontal scaling. 

### Provide pictures/videos of the behavior before and after these changes (optional)
Before:
415358392-8511c9eb-36d0-44ef-b3d0-14896e750269

After:

### Have you added or updated relevant tests?
- [ ] Yes
- [X] No changes are needed

### Have you added or updated relevant documentation?
- [ ] Yes
- [X] No changes are needed

### Are there any additional TODOs before this PR is ready to go?

TODOs:
- [ ] ...

### CODE REVIEW

File: frontend/src/Components/Charts/ChartAccessories/ExtraPairPlots/ExtraPairViolin.tsx [hunk 1]
```diff
@@ -28,6 +28,20 @@ type Props = {
...
+ * @param dataSet - The data set to get the domain from.
+ * @returns The x domain of the KDE from the data set.
+ */
+function getAttributeXDomain(dataSet: ExtraPairPoint['data']) {
+  const allKdeX: number[] = [];
+  Object.values(dataSet).forEach((result) => {
+    const originalKde = result.kdeArray;
+    allKdeX.push(...originalKde.map((point: { x: number }) => point.x));
+  });
+  return [min(allKdeX) ?? 0, max(allKdeX) ?? 20];
```
Comment (JackWilb) [inline frontend/src/Components/Charts/ChartAccessories/ExtraPairPlots/ExtraPairViolin.tsx:42]:
```suggestion
  
  const allKdeX = Object.values(dataSet).flatMap((result) => {
    const originalKde = result.kdeArray;
    return originalKde.map((point: { x: number }) => point.x);
  });
  return [min(allKdeX) ?? 0, max(allKdeX) ?? 20];
```

File: frontend/src/HelperFunctions/ExtraPairDataGenerator.ts [hunk 2]
```diff
@@ -30,6 +30,21 @@ const outcomeDataGenerate = (aggregatedBy: string, name: string, label: string,
...
+ * @returns The min and max of the object.
+ */
+function getAttributeMinMax(input: Record<string, number[]>): { attributeMin: number, attributeMax: number } {
+  let attributeData: number[] = [];
+  for (const key in input) {
+    if (Object.hasOwn(input, key)) {
+      attributeData = attributeData.concat(input[key]);
+    }
+  }
+  return { attributeMin: min(attributeData)!, attributeMax: max(attributeData)! };
```
Comment (JackWilb) [inline frontend/src/HelperFunctions/ExtraPairDataGenerator.ts:45]:
```suggestion
  const attributeData = Object.values(input).flat();
  return { attributeMin: min(attributeData)!, attributeMax: max(attributeData)! };
```

**Review by JackWilb — COMMENTED** [review]
Lets simplify

File: frontend/src/Components/Charts/ChartAccessories/ExtraPairPlots/ExtraPairViolin.tsx [hunk 3]
```diff
@@ -28,6 +28,20 @@ type Props = {
...
+ * Get the x domain of the KDE for the attribute.
+ * @param dataSet - The data set to get the domain from.
+ * @returns The x domain of the KDE from the data set.
+ */
+function getAttributeXDomain(dataSet: ExtraPairPoint['data']) {
+  
+  const allKdeX = Object.values(dataSet).flatMap((result) => {
+    const originalKde = result.kdeArray;
+    return originalKde.map((point: { x: number }) => point.x);
+  });
```
Comment (JackWilb) [inline frontend/src/Components/Charts/ChartAccessories/ExtraPairPlots/ExtraPairViolin.tsx:41]:
```suggestion
  const allKdeX = Object.values(dataSet).flatMap((result) => result.kdeArray.map((point: { x: number }) => point.x));
```

**Review by JackWilb — APPROVED** [review]
