### PR TITLE
Fix: Scatter Plot X-Axis Bin Labels (#307)

### LINKED ISSUE #307: Scatter plot's x-axis bins contain no labels
**Issue:** Scatter plots which contain bins on the x-axis have no labels inside of them. They are blank.

**Found with:** Luke's PC, development mode, random-dummy dataset.

Image

### PR DESCRIPTION
**Pull request by Luke-Schreiber**
### Does this PR close any open issues?
Closes #307 

### Give a longer description of what this PR addresses and why it's needed

**_Bug_**: Issue #307 Scatter plot x-axis bin labels did not contain text.
**_Fix_**: Scatter plot x-axis bin labels _now contain text._
**_Changes_**: 
- CustomizedAxisBand.tsx: Added a 'y' property to <AxisText> to vertically center text in bins.
- StyledSVGComponents.ts: Changed AxisText to 'styled.text'.

### Provide pictures/videos of the behavior before and after these changes (optional)
After:
issue307

### Have you added or updated relevant tests?
- [ ] Yes
- [X] No changes are needed

### Have you added or updated relevant documentation?
- [ ] Yes
- [X] No changes are needed

### Are there any additional TODOs before this PR is ready to go?

TODOs:
- [ ] ...

### CODE REVIEW

File: frontend/src/Presets/StyledSVGComponents.ts [hunk 1]
```diff
@@ -84,13 +84,11 @@ export interface BiggerFontProps {
...
 }
 
-export const AxisText = styled.foreignObject<BiggerFontProps>`
-    alignment-baseline: hanging;
-    y:0px;
-    text-align:center;
-      height: 13px;
-    font-size:${(props) => (props.biggerFont ? `${largeFontSize}px` : `${regularFontSize}px`)};
-    color:white;
+export const AxisText = styled.text<BiggerFontProps>`
```
Comment (JackWilb) [inline frontend/src/Presets/StyledSVGComponents.ts:87]: This change will cause issues. We need this to be a foreignObjects so that we can get truncation in the SVG. Please update to make it work with foreignObjects

**Review by JackWilb — CHANGES_REQUESTED** [review]

File: frontend/src/Presets/StyledSVGComponents.ts (hunk 1 above)
Comment (Luke-Schreiber) [reply frontend/src/Presets/StyledSVGComponents.ts]: That makes sense. In this new commit, I left StyledSVGComponents.ts alone, and instead only fixed the use of AxisText in CustomizedAxisBand.tsx. Let me know if this works.
